# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0003_auto_20171030_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.CharField(blank=True, choices=[('Moderated', 'Moderated'), ('Unmoderated', 'Unmoderated')], default='Unmoderated', max_length=128, null=True),
        ),
    ]
