# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0004_auto_20171030_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='publish',
        ),
        migrations.AddField(
            model_name='post',
            name='moderated',
            field=models.BooleanField(default=False),
        ),
    ]
