# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0006_auto_20171109_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
