"""
Django settings for website project.

Generated by 'django-admin startproject' using Django 1.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'rf&z$l^l4mm#o%e@h6qen=w!&0&w=%&f76509r0wu6ln4h1npc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['ronyroy.pythonanywhere.com','127.0.0.1']

SITE_ID = 1

# Application definition

INSTALLED_APPS = [
    'formapp',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.sites',
    'django.contrib.staticfiles',
    #'django_comments',
    'taggit',
    'shop',
    'cart',
    'orders',
    'social_django',
    'ckeditor',
    'ckeditor_uploader',
    'instamojo_wrapper',
    'star_ratings',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart',
                'social_django.context_processors.backends',  # <--
                'social_django.context_processors.login_redirect',      ],
        },
    },
]


WSGI_APPLICATION = 'website.wsgi.application'

AUTH_PROFILE_MODULE= 'profiles.Profile'
# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'rony29roy@gmail.com'
EMAIL_HOST_PASSWORD = 'rony1995'
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'rony29roy@gmail.com'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#Authentication
AUTHENTICATION_BACKENDS = (
    'social_core.backends.github.GithubOAuth2',
    'social_core.backends.twitter.TwitterOAuth',
    'social_core.backends.facebook.FacebookOAuth2',
    'social_core.backends.google.GoogleOpenId',
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.google.GoogleOAuth',
    'django.contrib.auth.backends.ModelBackend',
)
SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
)
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
    'fields': 'id,name,email', 
}
SOCIAL_AUTH_FORCE_EMAIL_VALIDATION = True
SOCIAL_AUTH_GITHUB_KEY = '4997059e3ada0e16e4d4'
SOCIAL_AUTH_GITHUB_SECRET = '175ca945b6e51c50bc4d875cb33c1e92b512434d'
SOCIAL_AUTH_FACEBOOK_KEY = '736545673195835'  # App ID
SOCIAL_AUTH_FACEBOOK_SECRET = '3ee20decc71859f8e25237461ec27605'  # App Secret
SOCIAL_AUTH_TWITTER_KEY = '9arVgSLIT8iGvSBsI6Aqaxgzn'
SOCIAL_AUTH_TWITTER_SECRET = 'PF9W5hzEoigD82QEIWSUH34A2ZhSKuoyewp8MqlJQQUdeVf0Bl'
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '21887722363-4ci5cb3lh97uo077ji9076itm8b4mmf8.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '1u49lIPNAmR09EaG4TjlXZvh'

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

TAGGIT_CASE_INSENSITIVE = True

MEDIA_ROOT=os.path.join(BASE_DIR,"media")

MEDIA_URL='/media/'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)
STATIC_ROOT = '/home/ronyroy/reviewhub/deployment/collected_static'
#SESSION_IDLE_TIMEOUT=1*60
SESSION_EXPIRE_AT_BROWSER_CLOSE=True
#SESSION_COOKIE_AGE=1*60   #DEFAULT IS 2 WEEKS IN SECONDS
LOGIN_REDIRECT_URL='/'
LOGIN_URL='/login/'

CART_SESSION_ID = 'cart'
CKEDITOR_UPLOAD_PATH = 'uploads/'
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': 700,
    },
}
CKEDITOR_UPLOAD_SLUGIFY_FILENAME = False

CKEDITOR_JQUERY_URL = '/static/js/jquery.min.js'
CKEDITOR_IMAGE_BACKEND = "pillow"
CKEDITOR_BROWSE_SHOW_DIRS = True
