# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20170815_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mobile',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
